---
- name: Install the Cuda Toolkit
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300

    - name: Gather facts for first time
      setup:

    - name: Execute the cuda installation script
      when: ansible_distribution == 'Ubuntu'
      script: files/cuda_installation.sh
